/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module mojo_top_0 (
    input clk,
    input rst_n,
    output reg [7:0] led,
    input cclk,
    output reg spi_miso,
    input spi_ss,
    input spi_mosi,
    input spi_sck,
    output reg [3:0] spi_channel,
    input avr_tx,
    output reg avr_rx,
    input avr_rx_busy,
    output reg [23:0] io_led,
    output reg [7:0] io_seg,
    output reg [3:0] io_sel,
    input [4:0] io_button,
    input [23:0] io_dip,
    output reg a,
    output reg b,
    output reg c,
    input sum,
    input carry
  );
  
  
  
  reg rst;
  
  wire [1-1:0] M_reset_cond_out;
  reg [1-1:0] M_reset_cond_in;
  reset_conditioner_1 reset_cond (
    .clk(clk),
    .in(M_reset_cond_in),
    .out(M_reset_cond_out)
  );
  localparam A0B0C0_state = 4'd0;
  localparam A0B0C1_state = 4'd1;
  localparam A0B1C0_state = 4'd2;
  localparam A0B1C1_state = 4'd3;
  localparam A1B0C0_state = 4'd4;
  localparam A1B0C1_state = 4'd5;
  localparam A1B1C0_state = 4'd6;
  localparam A1B1C1_state = 4'd7;
  localparam PASSED_state = 4'd8;
  localparam FAILED_state = 4'd9;
  localparam MANUAL_state = 4'd10;
  
  reg [3:0] M_state_d, M_state_q = A0B0C0_state;
  reg [26:0] M_clock_d, M_clock_q = 1'h0;
  reg [7:0] M_pass_d, M_pass_q = 1'h0;
  wire [8-1:0] M_ctr_value;
  counter_2 ctr (
    .clk(clk),
    .rst(rst),
    .value(M_ctr_value)
  );
  
  always @* begin
    M_state_d = M_state_q;
    M_clock_d = M_clock_q;
    M_pass_d = M_pass_q;
    
    M_reset_cond_in = ~rst_n;
    rst = M_reset_cond_out;
    led = 8'h00;
    spi_miso = 1'bz;
    spi_channel = 4'bzzzz;
    avr_rx = 1'bz;
    io_led = 24'h000000;
    io_seg = 8'hff;
    io_sel = 4'hf;
    M_clock_d = M_clock_q + 1'h1;
    io_led[16+7-:8] = M_pass_q;
    a = 1'h0;
    b = 1'h0;
    c = 1'h0;
    
    case (M_state_q)
      A0B0C0_state: begin
        a = 1'h0;
        b = 1'h0;
        c = 1'h0;
        io_led[0+0+0-:1] = 1'h1;
        if (sum == 1'h0 & carry == 1'h0) begin
          io_led[8+7-:8] = 8'hff;
          M_pass_d[0+0-:1] = 1'h1;
          io_led[16+7-:8] = M_pass_q;
        end
        if (M_clock_q[26+0-:1] == 1'h1) begin
          io_led[16+7-:8] = M_pass_q;
          M_state_d = A0B0C1_state;
          M_clock_d = 1'h0;
        end
      end
      A0B0C1_state: begin
        a = 1'h0;
        b = 1'h0;
        c = 1'h1;
        io_led[0+1+0-:1] = 1'h1;
        if (sum == 1'h1 & carry == 1'h0) begin
          io_led[8+7-:8] = 8'hff;
          M_pass_d[1+0-:1] = 1'h1;
          io_led[16+7-:8] = M_pass_q;
        end
        if (M_clock_q[26+0-:1] == 1'h1) begin
          io_led[16+7-:8] = M_pass_q;
          M_state_d = A0B1C0_state;
          M_clock_d = 1'h0;
        end
      end
      A0B1C0_state: begin
        a = 1'h0;
        b = 1'h1;
        c = 1'h0;
        io_led[0+2+0-:1] = 1'h1;
        if (sum == 1'h1 & carry == 1'h0) begin
          io_led[8+7-:8] = 8'hff;
          M_pass_d[2+0-:1] = 1'h1;
          io_led[16+7-:8] = M_pass_q;
        end
        if (M_clock_q[26+0-:1] == 1'h1) begin
          io_led[16+7-:8] = M_pass_q;
          M_state_d = A0B1C1_state;
          M_clock_d = 1'h0;
        end
      end
      A0B1C1_state: begin
        a = 1'h0;
        b = 1'h1;
        c = 1'h1;
        io_led[0+3+0-:1] = 1'h1;
        if (sum == 1'h0 & carry == 1'h1) begin
          io_led[8+7-:8] = 8'hff;
          M_pass_d[3+0-:1] = 1'h1;
          io_led[16+7-:8] = M_pass_q;
        end
        if (M_clock_q[26+0-:1] == 1'h1) begin
          io_led[16+7-:8] = M_pass_q;
          M_state_d = A1B0C0_state;
          M_clock_d = 1'h0;
        end
      end
      A1B0C0_state: begin
        a = 1'h1;
        b = 1'h0;
        c = 1'h0;
        io_led[0+4+0-:1] = 1'h1;
        if (sum == 1'h1 & carry == 1'h0) begin
          io_led[8+7-:8] = 8'hff;
          M_pass_d[4+0-:1] = 1'h1;
          io_led[16+7-:8] = M_pass_q;
        end
        if (M_clock_q[26+0-:1] == 1'h1) begin
          io_led[16+7-:8] = M_pass_q;
          M_state_d = A1B0C1_state;
          M_clock_d = 1'h0;
        end
      end
      A1B0C1_state: begin
        a = 1'h1;
        b = 1'h0;
        c = 1'h1;
        io_led[0+5+0-:1] = 1'h1;
        if (sum == 1'h0 & carry == 1'h1) begin
          io_led[8+7-:8] = 8'hff;
          M_pass_d[5+0-:1] = 1'h1;
          io_led[16+7-:8] = M_pass_q;
        end
        if (M_clock_q[26+0-:1] == 1'h1) begin
          io_led[16+7-:8] = M_pass_q;
          M_state_d = A1B1C0_state;
          M_clock_d = 1'h0;
        end
      end
      A1B1C0_state: begin
        a = 1'h1;
        b = 1'h1;
        c = 1'h0;
        io_led[0+6+0-:1] = 1'h1;
        if (sum == 1'h0 & carry == 1'h1) begin
          io_led[8+7-:8] = 8'hff;
          M_pass_d[6+0-:1] = 1'h1;
          io_led[16+7-:8] = M_pass_q;
        end
        if (M_clock_q[26+0-:1] == 1'h1) begin
          io_led[16+7-:8] = M_pass_q;
          M_state_d = A1B1C1_state;
          M_clock_d = 1'h0;
        end
      end
      A1B1C1_state: begin
        a = 1'h1;
        b = 1'h1;
        c = 1'h1;
        io_led[0+7+0-:1] = 1'h1;
        if (sum == 1'h1 & carry == 1'h1) begin
          io_led[8+7-:8] = 8'hff;
          M_pass_d[7+0-:1] = 1'h1;
          io_led[16+7-:8] = M_pass_q;
        end
        if (M_clock_q[26+0-:1] == 1'h1) begin
          io_led[16+7-:8] = M_pass_q;
          if (M_pass_q == 8'hff) begin
            M_state_d = PASSED_state;
          end else begin
            M_state_d = FAILED_state;
          end
        end
      end
      PASSED_state: begin
        M_clock_d = 1'h0;
        io_led[16+7-:8] = M_pass_q;
        io_led[0+7-:8] = 8'hff;
        io_led[8+7-:8] = 8'hff;
        if (M_clock_q[26+0-:1] == 1'h1) begin
          M_state_d = MANUAL_state;
        end
      end
      FAILED_state: begin
        M_clock_d = 1'h0;
        io_led[16+7-:8] = M_pass_q;
        if (M_clock_q[26+0-:1] == 1'h1) begin
          M_state_d = MANUAL_state;
        end
      end
      MANUAL_state: begin
        M_clock_d = 1'h0;
        a = io_dip[0+0+0-:1];
        b = io_dip[0+1+0-:1];
        c = io_dip[0+2+0-:1];
        if (M_clock_q[26+0-:1] == 1'h1) begin
          if (io_dip[0+0+0-:1] + io_dip[0+1+0-:1] + io_dip[0+2+0-:1] == (carry * 2'h2 + sum)) begin
            io_led[8+7-:8] = 8'hff;
          end else begin
            io_led[8+7-:8] = 8'h00;
          end
        end
      end
    endcase
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_clock_q <= 1'h0;
      M_pass_q <= 1'h0;
      M_state_q <= 1'h0;
    end else begin
      M_clock_q <= M_clock_d;
      M_pass_q <= M_pass_d;
      M_state_q <= M_state_d;
    end
  end
  
endmodule
